### ISSUE TITLE
Exception thrown when using dspot with Gradle automatic builder

### ISSUE THREAD

**Issue by MaelAudren** [STAMP-project/dspot#578] opened 2018-10-17 07:55 UTC
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**:  block
- **Tool/Service/Component**: dspot-1.1.0-jar-with-dependencies.jar
- **Execution Environment**: linux
- **Reporter**: Mael Audren, mael.audren@activeeon.com

#### Description

When using gradle automatic builder on the catalog project the following exception is thrown:
```
2018-10-17 09:39:28,611 INFO fr.inria.diversify.automaticbuilder.AutomaticBuilderFactory - Selected Gradle automatic builder.
Exception in thread "main" spoon.compiler.InvalidClassPathException: .jar does not exist, it is not a valid folder
	at spoon.support.StandardEnvironment.verifySourceClasspath(StandardEnvironment.java:424)
	at spoon.support.StandardEnvironment.setSourceClasspath(StandardEnvironment.java:414)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.setSourceClasspath(JDTBasedSpoonCompiler.java:306)
	at fr.inria.diversify.utils.compilation.DSpotCompiler.getSpoonModelOf(DSpotCompiler.java:104)
	at fr.inria.diversify.utils.compilation.DSpotCompiler.createDSpotCompiler(DSpotCompiler.java:31)
	at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:103)
	at fr.inria.stamp.Main.run(Main.java:58)
	at fr.inria.stamp.Main.run(Main.java:88)
	at fr.inria.stamp.Main.main(Main.java:41)
``` 

#### Steps to reproduce
Clone the catalog project
```shell
git clone https://github.com/ow2-proactive/catalog
```

Add the properties file in the root project then run the following command:
```shell
java -jar dspot-1.1.0-jar-with-dependencies.jar --path-to-properties dspot.properties --automatic-builder GradleBuilder
```

##### Properties file

```java
# Relative path to the project root.
project=.
# Path to the current module where we want to execute DSpot, relative to the project root
targetModule=.
# Relative path to the source project from this properties file
src=src/main/java/
# Relative path to the test source project from this properties file
testSrc=src/test/java
# Java version used
javaVersion=8
# (Optional) Path to the output folder, default to "output_diversify"
outputDirectory=dspot-out/
# (Optional) Filter on the package name containing tests to be amplified ("example" => "example.*")
filter=ow2.proactive.catalog.dto
```

**Comment by danglotb** [comment] 2018-10-17 08:02
Hi @MaelAudren 

Thank you for reporting this issue. I'm gonna investigate on this.

**Comment by danglotb** [comment] 2018-10-17 11:31
Hi @MaelAudren 
I found a bug and fixed in #581 
However, it seems that the GradleAutomaticBuilder does not work very well and require some debugging.
Since I did not developed it, I may need some time to do this.

**Comment by MaelAudren** [comment] 2018-10-17 12:20
Wow thanks for the quick answer @danglotb . I'll test the fix when it will be merge.

**Comment by monperrus** [comment] 2018-10-17 12:33
> Since I did not develop it

AFAIR, this is a nice contribution by Daniele. @danzone could you debug this one?

**Comment by danglotb** [comment] 2018-10-24 09:49
Hi,

@nicolabertazzo and @danzone I reproduced the issue.

The problem is when the `GradleAutomaticBuilder` modifies the existing `build.gradle`, it does not care if there is already `buildscript` and recreate it. 

So the `build.gradle` seems not to be valid and we cannot run anything.

I modified the `build.gradle` manually and successfully execute pit on **catalog** (with the same parameters than **DSpot** would). 

I'll propose a fix ASAP.

**Comment by danglotb** [comment] 2018-10-24 10:16
It appears that parsing and modifying a `build.gradle` file is very complex because it is a DSL and I could not find any gradle parser.

I propose a temporary workaround:

Gradle users should manually add the task and other stuff and we disable the injection done by **DSpot**.

This way, @MaelAudren  can start the experiment (with a bit more manual stuff) ASAP while we work on a more general and automatically way.
@nicolabertazzo  @danzone WDYT?

**Comment by danglotb** [comment] 2018-10-24 10:39
Okay, after trying to do so, I understand that we can't do this, because some dynamic options (_e.g._ the list of amplified tests for which we want to compute the mutation score) is specified with the file, and thus, the proposed workaround cannot be applied.

**Comment by danglotb** [comment] 2018-10-25 12:45
Hi, I did the fix, it almost done. I need to test it a bit.

I'll propose a pull request as soon as possible.

**Comment by danglotb** [comment] 2018-10-25 16:00
I merged #609.

Please pull and retry.

You must update your `dspot.properties` file with:

```
# Relative path to the project root.
project=.
# Relative path to the source project from this properties file
src=src/main/java/
# Relative path to the test source project from this properties file
testSrc=src/test/java/
# Java version used
javaVersion=8
# (Optional) Path to the output folder, default to "output_diversify"
outputDirectory=dspot-out/
# (Optional) Filter on the package name containing tests to be amplified ("example" => "example.*")
filter=org.ow2.proactive.catalog.*
classes=build/classes/main/
testClasses=build/classes/test/
```

Since you use a gradle project, you must specify the folders of binaries with:
```
classes=build/classes/main/
testClasses=build/classes/test/
```

Also I think you filter was wrong:

```
filter=org.ow2.proactive.catalog.*
```

missing the `org` at the begin.

**Comment by danglotb** [comment] 2018-10-25 22:38
Could you retry when #615 is merged? Thank you!

**Comment by MaelAudren** [comment] 2018-10-26 09:59
@danglotb I managed to build successfully a dspot report by running the following command 
`java -jar dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties --automatic-builder GradleBuilder --test=ow2.proactive.catalog.dto.BucketMetadataTest` on my project.
Thanks a lot.

**Comment by danglotb** [comment] 2018-10-26 10:44
Happy to hear that! Enjoy!

**Closed by danglotb** 2018-10-26 10:44 UTC
Labels: bug, high priority
