### ISSUE TITLE
--example not working

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/dspot#557] opened 2018-09-25 11:29 UTC
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot 1.1.1
- **Execution Environment**: Windows 10
- **Reporter**: Lars Thomas Boye

#### Description
Starting to test DSpot again, I tried to run with --example as described in the readme. I get a compilation error (see below). I have JAVA_HOME pointing to a Java 8 jdk.

##### Command Line / Options

java -jar target/dspot-USED-VERSION-jar-with-dependencies.jar --example

[INFO] 2018-09-25 13:25:38 EntryPoint - Path to runner Classes: E:\Dev\stamp\dspot\dspot\target\dspot.jar
[INFO] 2018-09-25 13:25:38 EntryPoint - E:\Dev\stamp\dspot\dspot\target\dspot.jar
[INFO] 2018-09-25 13:25:38 EntryPoint - E:\Dev\stamp\dspot\dspot\target\dspot.jar
[INFO] 2018-09-25 13:25:38 EntryPoint - E:\Dev\stamp\dspot\dspot\target\dspot.jar
[WARN] 2018-09-25 13:25:38 AutomaticBuilderFactory - automaticBuilderName: unknown automatic builder specified in configuration, going to default.
[INFO] 2018-09-25 13:25:38 AutomaticBuilderFactory - Default: provided Maven automatic builder.
[INFO] 2018-09-25 13:25:38 MavenAutomaticBuilder - run maven clean test -DskipTests dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< example:example >---------------------------
[INFO] Building test-projects 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ example ---
[INFO] Deleting E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ example ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.100 s
[INFO] Finished at: 2018-09-25T13:25:40+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project example: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\target\dspot\classpath (Systemet finner ikke angitt bane)
        at eu.stamp_project.Main.runExample(Main.java:101)
        at eu.stamp_project.Main.main(Main.java:38)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\target\dspot\classpath (Systemet finner ikke angitt bane)
        at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.compileAndBuildClasspath(MavenAutomaticBuilder.java:91)
        at eu.stamp_project.program.InputConfiguration.initializeBuilder(InputConfiguration.java:150)
        at eu.stamp_project.program.InputConfiguration.initialize(InputConfiguration.java:101)
        at eu.stamp_project.program.InputConfiguration.initialize(InputConfiguration.java:71)
        at eu.stamp_project.Main.runExample(Main.java:95)
        ... 1 more
Caused by: java.io.FileNotFoundException: E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\target\dspot\classpath (Systemet finner ikke angitt bane)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.compileAndBuildClasspath(MavenAutomaticBuilder.java:88)
        ... 5 more

**Comment by ltboye** [comment] 2018-09-25 11:41
Same error also when trying to run on a real project.

**Comment by danglotb** [comment] 2018-09-25 11:55
It appears that your `JAVA_HOME` and maven are not properly set up:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project example: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
```

A suggest to you to fix your maven install by making the environment variable JAVA_HOME pointing to a JDK.

After a quick look, I found a plenty solutions, _e.g._ [this](https://stackoverflow.com/questions/15279586/java-home-in-maven)

Cheers

**Comment by ltboye** [comment] 2018-09-25 12:04
As I said, JAVA_HOME points to a Java 8 jdk, so it is correct.

From mvn -version:
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: C:\Dev\apache-maven-3.5.4\bin\..
Java version: 1.8.0_172, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_172\jre
Default locale: no_NO, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

The path shown in mvn -version is the correct jdk. It adds \jre, which is correct according to the stackoverflow link you gave above.

**Comment by danglotb** [comment] 2018-09-25 12:12
Do you have more than one maven installation? Could you please look at the values of the following environment variables: `MAVEN_HOME`, `M2_HOME`?

> As I said, JAVA_HOME points to a Java 8 jdk, so it is correct.

Sorry, read to fast.

Best.

**Comment by ltboye** [comment] 2018-09-25 12:44
I do have an older maven installation on my machine (3.3.9). Should I remove it?
MAVEN_HOME is C:\Dev\apache-maven-3.5.4, which is the version I currently use. This with \bin is included in PATH.

I do not have M2_HOME. Interestingly, according to 3.5 release notes, it is no longer supported:
https://maven.apache.org/docs/3.5.0/release-notes.html

**Comment by danglotb** [comment] 2018-09-25 12:52
> I do have an older maven installation on my machine (3.3.9). Should I remove it?

Could you? It will remove one of my doubt :)

> I do not have M2_HOME. Interestingly, according to 3.5 release notes, it is no longer supported:
https://maven.apache.org/docs/3.5.0/release-notes.html

Thank you for the pointer

**Comment by ltboye** [comment] 2018-09-25 13:04
I deleted the old maven (I don't use it any more anyway). Still the same error when trying to run dspot.

**Comment by danglotb** [comment] 2018-10-02 12:31
Hi @ltboye 

Could you retry and copy/paste the full logs of the execution? I added some logs.

Since I cannot reproduce on my side the errors, it is complicated for me to understand what is happening.

**Comment by ltboye** [comment] 2018-10-02 12:53
Sure, this is after building the latest from master:

2018-10-02 14:48:25,120 INFO eu.stamp_project.testrunner.EntryPoint - Path to runner Classes: E:\Dev\stamp\dspot\dspot\target\dspot.jar
2018-10-02 14:48:25,120 INFO eu.stamp_project.testrunner.EntryPoint - E:\Dev\stamp\dspot\dspot\target\dspot.jar
2018-10-02 14:48:25,120 INFO eu.stamp_project.testrunner.EntryPoint - E:\Dev\stamp\dspot\dspot\target\dspot.jar
2018-10-02 14:48:25,120 INFO eu.stamp_project.testrunner.EntryPoint - E:\Dev\stamp\dspot\dspot\target\dspot.jar
2018-10-02 14:48:25,120 WARN eu.stamp_project.automaticbuilder.AutomaticBuilderFactory - automaticBuilderName: unknown automatic builder specified in configuration, going to default.
2018-10-02 14:48:25,120 INFO eu.stamp_project.automaticbuilder.AutomaticBuilderFactory - Default: provided Maven automatic builder.
2018-10-02 14:48:25,135 INFO eu.stamp_project.automaticbuilder.MavenAutomaticBuilder - Using C:\Dev\apache-maven-3.5.4 for maven home
2018-10-02 14:48:25,135 INFO eu.stamp_project.automaticbuilder.MavenAutomaticBuilder - run maven: C:\Dev\apache-maven-3.5.4/bin/mvn clean test -DskipTests dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< example:example >---------------------------
[INFO] Building test-projects 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ example ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ example ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ example ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.454 s
[INFO] Finished at: 2018-10-02T14:48:28+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project example: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\target\dspot\classpath (Systemet finner ikke angitt bane)
        at eu.stamp_project.Main.runExample(Main.java:101)
        at eu.stamp_project.Main.main(Main.java:38)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\target\dspot\classpath (Systemet finner ikke angitt bane)
        at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.compileAndBuildClasspath(MavenAutomaticBuilder.java:91)
        at eu.stamp_project.program.InputConfiguration.initializeBuilder(InputConfiguration.java:150)
        at eu.stamp_project.program.InputConfiguration.initialize(InputConfiguration.java:101)
        at eu.stamp_project.program.InputConfiguration.initialize(InputConfiguration.java:71)
        at eu.stamp_project.Main.runExample(Main.java:95)
        ... 1 more
Caused by: java.io.FileNotFoundException: E:\Dev\stamp\dspot\dspot\src\test\resources\test-projects\target\dspot\classpath (Systemet finner ikke angitt bane)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.compileAndBuildClasspath(MavenAutomaticBuilder.java:88)
        ... 5 more

**Comment by danglotb** [comment] 2018-10-02 13:10
I am sorry, but I don't know.

Is it possible that maven does not find its maven home because you are executing **DSpot** on `E:` and maven is installed on `C:`?

I ran out of ideas, I am sorry.

**Comment by ltboye** [comment] 2018-10-02 13:17
I will try to move DSpot to C:.

Have you verified this version of DSpot working on Windows 10?

**Comment by ltboye** [comment] 2018-10-17 11:06
Hi @danglotb 

Looking at this issue again, I have found two suggestions which may be worth trying.

One is to run Maven with -Dtools_jar_location <path of tools.jar>

The other is to add this configuration to the maven-compiler-plugin in the pom:
<configuration>
    <executable>path to javac.exe</executable>
</configuration>

Is it possible for me to try these things by modifying the DSpot source? If you point out where, I can try to experiment.

**Comment by danglotb** [comment] 2018-10-17 12:59
Hi @ltboye 

I am not sure that I understand your solution.

But, if you want to add an option in the maven goals you can have a look to the `eu.stamp_project.automaticbuilder.MavenAutomaticBuilder` class.

More precisely, the method [`runGoals()`](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/eu/stamp_project/automaticbuilder/MavenAutomaticBuilder.java#L238) which the method that actually run the `mvn` command with specific goals (_.e.g_ `mvn clean test` to clean and launch the test of the project).

> The other is to add this configuration to the maven-compiler-plugin in the pom:

I do not like the idea of modifying the `pom.xml` automatically of the "client" project because no one likes that a bot touch our stuff and it can be messy.

**Comment by danglotb** [comment] 2019-04-15 07:56
Closing this issue. Please reopen it or open a new one. Thank you.

**Closed by danglotb** 2019-04-15 07:56 UTC
