### ISSUE TITLE
add support for "mvn stamp:dspot"

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/dspot#51] opened 2017-01-27 14:35 UTC
Motivation: running Dspot on the command-line is tedious, having a Maven task specific for Stamp would result in suimply calling `mvn stamp` or `mvn amplify` on any arbitrary project (For example, "mvn pit" is the same thing for mutation testing

Output: Calling `mvn stamp` would use a default amplification configuration and the amplified test would be written in `target/stamp-amplified`

**Comment by nicolabertazzo** [comment] 2017-09-05 15:44
Hi @danglotb ,

I started to develop the dspot maven plugin on https://github.com/nicolabertazzo/dspot/tree/maven-plugin.
I found some problem using dspot. When I try to execute dspot from a project's directory (different from dspot) I had this issue: dspot try to create many times this folder target/tmpDir/  (target/tmpDir/tmp/target/tmpDir)

**Comment by danglotb** [comment] 2017-09-06 07:39
Hello @nicolabertazzo 

Thank you for working on a maven plugin, that's a great news!

Thank you for reporting the bug! I'll prepare a fix ASAP.

Cheers.

**Comment by danglotb** [comment] 2017-09-06 19:15
Hello, I just merged #173. The problem should be fixed.

**Comment by nicolabertazzo** [comment] 2017-10-04 09:15
Hello @danglotb,
For the maven plugin development I need the source code of this class:
import fr.inria.diversify.runner.InputConfiguration
Could you give me a link of this file or send to me the source code?

**Comment by danglotb** [comment] 2017-10-04 10:47
HI @nicolabertazzo 

`fr.inria.diversify.runner.InputConfiguration` come from [sosifier](https://github.com/DIVERSIFY-project/sosiefier)

You can find the java file [here](https://github.com/DIVERSIFY-project/sosiefier/blob/master/core/src/main/java/fr/inria/diversify/runner/InputConfiguration.java)

However, I think that DSpot should not have these dependencies to modules of sosifier. 

I started to refactor DSpot to remove them, see #189. But there is a lot of work.

**Comment by danglotb** [comment] 2017-10-05 12:06
Hi @nicolabertazzo 

I'll changes the visibilities of methods [stringToAmplifier](https://github.com/STAMP-project/dspot/blob/master/src/main/java/fr/inria/stamp/JSAPOptions.java#L128), [buildAmplifiersFromString](https://github.com/STAMP-project/dspot/blob/master/src/main/java/fr/inria/stamp/JSAPOptions.java#L132) and enums [SelectorEnum](https://github.com/STAMP-project/dspot/blob/master/src/main/java/fr/inria/stamp/JSAPOptions.java#L30), [AmplifierEnum](https://github.com/STAMP-project/dspot/blob/master/src/main/java/fr/inria/stamp/JSAPOptions.java#L64), in the class [fr.inria.stamp.JSAPOptions](https://github.com/STAMP-project/dspot/blob/master/src/main/java/fr/inria/stamp/JSAPOptions.java). 

You will be able to create the configuration from strings [see](https://github.com/STAMP-project/dspot/blob/master/src/main/java/fr/inria/stamp/JSAPOptions.java#L114).

see #206

**Comment by nicolabertazzo** [comment] 2017-10-10 14:24
Hi @danglotb,

I incurred some problem during the development of the dspot maven plugin, so I need your help to to solve these.

The problems are:
1) I'm not able to copy dspot dependencies:
DSpotUtils.copyPackageFromResources:
	dspot/dependencies/fr/inria/diversify/compare/MethodsHandler.class
	dspot/dependencies/fr/inria/diversify/compare/ObjectLog.class
	dspot/dependencies/fr/inria/diversify/compare/Observation.class
	dspot/dependencies/fr/inria/diversify/compare/Utils.class
ClassLoader.getSystemResourceAsStream returns always a null Object.

2) I try to run dspot from the maven plugin and I have this error:
00:07 INFO: run maven  org.pitest:pitest-maven:mutationCoverage -DwithHistory -DtargetClasses=null -DreportsDirectory=target/pit-reports -DoutputFormats=CSV,HTML -DtimeoutConst=10000 -DjvmArgs=16G -DmutationEngines=gregor -Dmutators=ALL -DadditionalClasspathElements=target/dspot/dependencies/ 
java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
[INFO] ------------------------------------------------------------------------
	at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:196)
	at fr.inria.diversify.dspot.selector.PitMutantScoreSelector.init(PitMutantScoreSelector.java:56)
	at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:114)
	at fr.inria.stamp.Main.run(Main.java:50)
	at fr.inria.diversify.dspot.maven.DSpotMojo.execute(DSpotMojo.java:117)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:189)
	... 26 more

If you want to try the plugin you can clone this project:
https://github.com/nicolabertazzo/dspot.git

checkout the branch:
maven-plugin

run mvn clean install -DskipTests

From dspot/dspot/src/test/resources/test-projects
run this command:
mvn compile fr.inria.diversify:dspot-maven:1.0.0:mutationCoverage -X 

We look forward to receiving your reply,

Nicola

**Comment by nicolabertazzo** [comment] 2017-11-07 15:43
Hi @danglotb ,

Have you some news about the issue reported on the 10th of October?

I have the same problem if I try to execute DSpot from maven using the follow command:
mvn exec:java -Dexec.mainClass="fr.inria.stamp.Main" -X -Dexec.args="-e"

Nicola

**Comment by danglotb** [comment] 2017-11-08 09:51
Hello @nicolabertazzo 

The branch `maven-plugin` does not exist anymore on your fork.

But, I still had a copy locally. 

I just rebase it, with our previous changes.

You can find it now on my own fork: [danglotb/maven-plugin](https://github.com/danglotb/dspot/tree/maven-plugin).

I fixed the issue about the copy of resources. 

But, we are facing a new problem: when executing with maven, it seems that **DSpot** is not able anymore to run test, because of the [`fr.inria.stamp.test.filter.MethodFilter`](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/fr/inria/stamp/test/filter/MethodFilter.java#L23). If you try by yourself, you will see the following message:
`WARN fr.inria.diversify.dspot.Amplification - Need a green test suite to run dspot` 
_i.e._ when **DSpot** runs tests, some of them are failing (before amplification). I take a look deeper to errors, and it is: `initializationError(example.TestSuiteExample): No runnable methods`.

**DSpot**'s filter is not executed (when I added trace of the execution). 

I think it is because maven execution has its own classloader, and some classes is already loaded that's create a conflict.

I look to resolve this issue, but it is quite tricky and might take some time.

Cheers,

-- Benjamin.

**Comment by danglotb** [comment] 2017-11-08 12:08
Hi @nicolabertazzo 

I pushed some changes on the branch [danglotb/maven-plugin](https://github.com/danglotb/dspot/tree/maven-plugin).

I was able to run dspot using `mvn exec:java -Dexec.mainClass="fr.inria.stamp.Main" -X -Dexec.args="-e"`.

I also run the maven-plugin on test-projects, but it seems some configurations are missing.

Would you mind to have a look?

I suggest you to retrieve the branch  [danglotb/maven-plugin](https://github.com/danglotb/dspot/tree/maven-plugin), and add it to your own fork.

Thank you very much.

-- Benjamin.

**Comment by nicolabertazzo** [comment] 2017-11-08 16:33
Hi @danglotb,

I worked on maven-plugin and i done these tasks:
- I manualy merged my branch https://github.com/nicolabertazzo/dspot/tree/module-structure with your branch  https://github.com/danglotb/dspot/tree/maven-plugin (I suggest to delete these branch on your fork because it's not updated)
- I fixed a problem about the filter parmeter (I'm still working on it)
- I merged https://github.com/STAMP-project/dspot/tree/master with my branch https://github.com/nicolabertazzo/dspot/tree/module-structure and pushed to my fork.

Now the branch https://github.com/nicolabertazzo/dspot/tree/module-structure.
It still has some problem but now, if you perform the command:
 mvn -f dspot/src/test/resources/test-projects/pom.xml clean package  fr.inria.stamp:dspot-maven:1.0.0:mutationCoverage 

it works, the amplified tests are generated, but I have a maven error at the end.
I'll update you as soon as I'll have some news (or I'll create a pull request)

**Comment by nicolabertazzo** [comment] 2017-11-09 15:03
Hi @danglotb,

The dspot maven-plugin works!
I tryed it on https://github.com/STAMP-project/dhell project using these commands:
- executed
`mvn clean install -DskipTests from this branch https://github.com/nicolabertazzo/dspot/tree/module-structure`
from https://github.com/nicolabertazzo/dspot/tree/module-structure branch
- cloned dhell project https://github.com/STAMP-project/dhell
- from dhell project folder executed
`mvn clean package  fr.inria.stamp:dspot-maven:1.0.0:mutationCoverage -Dfilter=fr.inria.stamp.examples.dhell*`

Dspot produced the amplification but return these problems:
`java.lang.RuntimeException: spoon.compiler.ModelBuildingException: The import fr.inria.stamp.examples.dhell.HelloApp cannot be resolved at /home/bertazzo/Progetti/2017/dspot/dhell/src/test/java/fr/inria/stamp/examples/dhell/HelloAppTest.java:7
[INFO] ------------------------------------------------------------------------
	at fr.inria.stamp.Main.amplifyAll(Main.java:138)
	at fr.inria.stamp.Main.run(Main.java:87)
	at fr.inria.diversify.dspot.maven.DSpotMojo.execute(DSpotMojo.java:121)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: spoon.compiler.ModelBuildingException: The import fr.inria.stamp.examples.dhell.HelloApp cannot be resolved at /home/bertazzo/Progetti/2017/dspot/dhell/src/test/java/fr/inria/stamp/examples/dhell/HelloAppTest.java:7
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:581)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:562)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:119)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:100)
	at spoon.Launcher.buildModel(Launcher.java:709)
	at fr.inria.diversify.dspot.support.DSpotCompiler.compile(DSpotCompiler.java:127)
	at fr.inria.diversify.utils.Initializer.compileTest(Initializer.java:84)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:186)
	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:157)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at fr.inria.diversify.dspot.DSpot.amplifyAllTests(DSpot.java:126)
	at fr.inria.stamp.Main.amplifyAll(Main.java:136)
	... 24 more`

I tryed to debug and the problem is in this method: https://github.com/nicolabertazzo/dspot/blob/8dc0b09324a573e40285763d9621b590e20e8c82/dspot/src/main/java/fr/inria/diversify/utils/Initializer.java#L72
Can you help me to solve this problem?

Tnx

**Comment by danglotb** [comment] 2017-11-09 17:55
Hi @nicolabertazzo 

That's great! Good job! Thank you very much! :+1: 

I identified a problem in the initialization of the input configuration [here](https://github.com/nicolabertazzo/dspot/blob/8dc0b09324a573e40285763d9621b590e20e8c82/dspot-maven/src/main/java/fr/inria/diversify/dspot/maven/DSpotMojo.java#L119)

You pass two times ` getTestClassesDir()`, while one of this value (the first if I am right) should ` getClassesDir()`

Those two values points respectively directories of compiled sources and test sources. DSpot could not find the compiled sources, which are required to compile tests.

On my side, I fixed that and the amplification kept going after that, _i.e._ **DSpot** amplifies the next test case. 

One remark about the maven plugin. I think we should not create a new InputConfiguration, namely `MyInputConfiguration`, but rather modify the exist one (which is not longer in sosiefier, I brang it into **DSpot** several PRs ago).

Could you please, remove this extra class, and modify the [fr.inria.diversify.utils.sosiefier.InputConfiguration](https://github.com/nicolabertazzo/dspot/blob/8dc0b09324a573e40285763d9621b590e20e8c82/dspot/src/main/java/fr/inria/diversify/utils/sosiefier/InputConfiguration.java#L28) because I planned to refactor some classes (or all) from the sosiefier package.

Thank you! Great job!

-- Benjamin.

**Comment by nicolabertazzo** [comment] 2017-11-10 09:16
Hi @danglotb ,

I took your advice and i fix the problem about the inizializiation of input configuration in my class.
Now the maven plugin works and i tag the commit here https://github.com/nicolabertazzo/dspot/releases/tag/maven-pluginV1.0.

Ok we can refactor the InputConfiguration Class and remove MyInputConfiguration.
I suggest also to refactor all the relative path to absolute path.

I'will open a issue to track the activity and I'll open a new branch on my fork.

**Comment by danglotb** [comment] 2018-06-18 15:31
Hi @nicolabertazzo 

See #453 which a huge refactor of the InputConfiguration object.

**Comment by danglotb** [comment] 2018-07-06 22:13
Hi

I finished #453 with a huge refactor of the InputConfiguration object.

I also refactored the DSpotMojo. The mojo is now a simply proxy for the command line and call the main method.

For now, I wrote some tests but we may need to improve them.

I'm gonna close this issue, since the mojo seems to work great.

**Closed by danglotb** 2018-07-06 22:13 UTC
Labels: enhancement
