### ISSUE TITLE
--useReflection doesn't work

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#287] opened 2017-12-13 16:15 UTC
Happens on v1.0.4-SNAPSHOT built from sources on 13 dec, 16:00.

Issue found on xwiki-commons-xml

**Comment by monperrus** [comment] 2017-12-13 17:54
it's not even a regression, it has probably never worked :-)

**Comment by danglotb** [comment] 2018-02-08 13:57
This feature won't be implemented since we will use a test runner that launch a new JVM.

see #301

**Comment by monperrus** [comment] 2018-02-09 08:38
Should we remove the flag from the code and the documentation then?

**Comment by danglotb** [comment] 2018-02-09 10:16
see #321 .

**Closed by danglotb** 2018-02-09 10:16 UTC
