### ISSUE TITLE
Generated tests should use the same JUnit5 version as original test

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#689] opened 2019-02-04 10:02 UTC
Here's a generated test based on a JUnit5 test:

```
package org.xwiki.filter.type;


import org.junit.Assert;
import org.junit.jupiter.api.Test;


/**
 * Validate {@link FilterStreamType}.
 *
 * @version $Id: 14e8427db206cf2676efda12475b90e187536d14 $
 */
public class AmplFilterStreamTypeTest {
    // Tests
    @org.junit.Test(timeout = 10000)
    public void testSerializeWithDataAndVersionlitString40306() throws Exception {
        FilterStreamType type = new FilterStreamType(new SystemType("type"), "data", ":");
        // AssertGenerator add assertion
        Assert.assertEquals("type+data/:", ((FilterStreamType) (type)).toString());
        // AssertGenerator add assertion
...
```

Notice the usage of:
* `import org.junit.Assert;` --> JUnit 4
*  `@org.junit.Test` --> JUnit 4
*  `import org.junit.jupiter.api.Test;` --> JUnit 5 (but not used)

Original test:

```
package org.xwiki.filter.type;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Validate {@link FilterStreamType}.
 *
 * @version $Id: 14e8427db206cf2676efda12475b90e187536d14 $
 */
public class FilterStreamTypeTest
{
    // Tests

    @Test
    public void testSerializeWithDataAndVersion()
    {
        FilterStreamType type = new FilterStreamType(new SystemType("type"), "data", "version");

        assertEquals("type+data/version", type.serialize());
    }
...
```

**Comment by danglotb** [comment] 2019-02-04 12:35
Hello @vmassol 

Could you give more information about your execution? I cannot reproduce.

Here what I obtain when I amplify the same test class:

```java
@org.junit.jupiter.api.Test
    public void testUnserializeWithDataAndVersion() throws java.lang.Exception {
        org.xwiki.filter.type.FilterStreamType type = org.xwiki.filter.type.FilterStreamType.unserialize("type+data/version");
        org.junit.jupiter.api.Assertions.assertEquals("data", ((org.xwiki.filter.type.FilterStreamType) (type)).getDataFormat());
        org.junit.jupiter.api.Assertions.assertEquals("version", ((org.xwiki.filter.type.FilterStreamType) (type)).getVersion());
        org.junit.jupiter.api.Assertions.assertEquals("type+data/version", ((org.xwiki.filter.type.FilterStreamType) (type)).toString());
        org.junit.jupiter.api.Assertions.assertEquals(1066324289, ((int) (((org.xwiki.filter.type.FilterStreamType) (type)).hashCode())));
        org.junit.jupiter.api.Assertions.assertEquals("type", ((org.xwiki.filter.type.SystemType) (((org.xwiki.filter.type.FilterStreamType) (type)).getType())).toString());
....
```

With the following options `--path-to-properties xwiki.properties --descartes --verbose --generate-new-test-class --test org.xwiki.filter.type.FilterStreamTypeTest --test-criterion JacocoCoverageSelector`

On the current SNAPSHOT, _i.e._ `1.2.4-SNAPSHOT`.

**Comment by vmassol** [comment] 2019-02-04 12:37
* Location: xwiki-commons-filter-api/
* Dspot.properties:

```
project=../../../
targetModule=xwiki-commons-core/xwiki-commons-filter/xwiki-commons-filter-api
src=src/main/java/
testSrc=src/test/java/
testResources=src/test/resources/
javaVersion=8
outputDirectory=output
filter=org.xwiki.*
srcResources=src/main/resources/
```

* Dspot config:

```
        <plugin>
          <groupId>eu.stamp-project</groupId>
          <artifactId>dspot-maven</artifactId>
          <version>1.2.1</version>
          <configuration>
            <clean>true</clean>
            <descartes>true</descartes>
            <verbose>true</verbose>
            <withComment>true</withComment>
            <generateNewTestClass>true</generateNewTestClass>
            <pathToProperties>./dspot.properties</pathToProperties>
            <amplifiers>
              <!-- Uncomment the amplifier to use or pass them on the command line using -Damplifiers=... -->
              <!--amplifier>StringLiteralAmplifier</amplifier-->
              <!--amplifier>NumberLiteralAmplifier</amplifier-->
              <!--amplifier>CharLiteralAmplifier</amplifier-->
              <!--amplifier>BooleanLiteralAmplifier</amplifier-->
              <!--amplifier>AllLiteralAmplifiers</amplifier>
              <amplifier>MethodAdd</amplifier>
              <amplifier>MethodRemove</amplifier>
              <amplifier>MethodGeneratorAmplifier</amplifier>
              <amplifier>ReturnValueAmplifier</amplifier>
              <amplifier>ReplacementAmplifier</amplifier>
              <amplifier>NullifierAmplifier</amplifier-->
            </amplifiers>
          </configuration>
        </plugin>
```

* Command line: mvn dspot:amplify-unit-tests

**Comment by danglotb** [comment] 2019-02-04 12:54
The complete support of JUnit5 has been introduced in [DSpot 1.2.2](https://github.com/STAMP-project/dspot/releases/tag/dspot-1.2.2) with the Test framework feature. 

Please upgrade the version DSpot that you are using.

**Comment by danglotb** [comment] 2019-02-04 14:10
I'm closing this one.

**Closed by danglotb** 2019-02-04 14:10 UTC
Labels: misuse
