### ISSUE TITLE
java.io.FileNotFoundException: E:\Atos\STAMP\Git\dhell\.\target\dspot\classpath (The system cannot find the path specified)

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#457] opened 2018-06-06 13:08 UTC
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot, latest compiled version from Github repository
- **Execution Environment**: Windows 10, Windows 7
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
DSpot is not working when applied on Dhell on Windows 7/10 with default configuration, using default dspot.properties and pom.xml (just dhell cloned from repository). Same configuration in Linux works well.

#### Steps to reproduce
Follow DSpot to get, build and package
Follow DHell to get, build and package

From Dhell folder, execute:
`java -jar ..\dspot\dspot\target\dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties .\dspot.properties`

Dspot triggers this exception:
```
E:\Atos\STAMP\Git\dhell>java -jar ..\dspot\dspot\target\dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties .\dspot.properties --verbose
2018-06-06 15:05:25,167 WARN eu.stamp_project.automaticbuilder.AutomaticBuilderFactory - No automatic builder specified in configuration, going to default.
2018-06-06 15:05:25,167 INFO eu.stamp_project.automaticbuilder.AutomaticBuilderFactory - Default: provided Maven automatic builder.
2018-06-06 15:05:25,200 INFO eu.stamp_project.automaticbuilder.MavenAutomaticBuilder - run maven dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building hello_app 1.2.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:build-classpath (default-cli) @ hello_app ---
[INFO] Wrote classpath file 'E:\Atos\STAMP\Git\dhell\target\dspot\classpath'.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.715 s
[INFO] Finished at: 2018-06-06T15:05:43+02:00
[INFO] Final Memory: 13M/95M
[INFO] ------------------------------------------------------------------------
2018-06-06 15:05:44,000 INFO eu.stamp_project.automaticbuilder.AutomaticBuilderFactory - Selected Maven automatic builder.
2018-06-06 15:05:44,000 INFO eu.stamp_project.automaticbuilder.MavenAutomaticBuilder - run maven clean test -DskipTests dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building hello_app 1.2.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ hello_app ---
[INFO] Deleting E:\Atos\STAMP\Git\dhell\target
[INFO] Deleting E:\Atos\STAMP\Git\dhell (includes = [*.txt, *.traces, *.log], excludes = [])
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hello_app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\Atos\STAMP\Git\dhell\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hello_app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to E:\Atos\STAMP\Git\dhell\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.577 s
[INFO] Finished at: 2018-06-06T15:05:50+02:00
[INFO] Final Memory: 10M/95M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project hello_app: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: E:\Atos\STAMP\Git\dhell\.\target\dspot\classpath (The system cannot find the path specified)
        at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.compile(MavenAutomaticBuilder.java:77)
        at eu.stamp_project.utils.Initializer.initialize(Initializer.java:20)
        at eu.stamp_project.dspot.DSpot.<init>(DSpot.java:88)
        at eu.stamp_project.Main.run(Main.java:57)
        at eu.stamp_project.Main.run(Main.java:91)
        at eu.stamp_project.Main.main(Main.java:42)
Caused by: java.io.FileNotFoundException: E:\Atos\STAMP\Git\dhell\.\target\dspot\classpath (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at eu.stamp_project.automaticbuilder.MavenAutomaticBuilder.compile(MavenAutomaticBuilder.java:74)
        ... 5 more
```

##### Properties file

```#relative path to the target project root from dspot execution

project=./
#relative path to the source project from the project properties

src=src/main/java/

#relative path to the test source project from the project properties

testSrc=src/test/java

#java version used

javaVersion=8

# (optional) path to the output folder, default to "output_diversify"

outputDirectory=dspot-out/

# (optional) filter on the package name containing tests to be amplified ("example" => "example.*"

filter=fr.inria.stamp.examples.dhell*

```

##### Command Line / Options

```shell
java -jar ..\dspot\dspot\target\dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties .\dspot.properties
```

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by arnobl** [comment] 2018-06-18 12:54
Same problem with 1.1.0 and 1.0.7
No maven module.

```
project=.
targetModule=.
src=src/main/java/
testSrc=src/test/java
javaVersion=8
outputDirectory=target/dspot-out/
filter=net.sf.latexdraw.models.*
```

**Comment by danglotb** [comment] 2018-06-18 15:09
Hi,

According to the trace, it seems that your maven configuration is wrong:

`[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?`

When **DSpot** tries to collect the classpath with `mvn dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath`

Could you please, check your installation?

**Comment by arnobl** [comment] 2018-06-18 15:42
In fact I was running Java 10 (I do not know why). Fixed by using Java8.

**Comment by RicardoTej** [comment] 2018-06-20 12:02
Hello :

I have a similar problem when trying java -jar .../dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties .../dspot.properties.

I'm using Windows 7, Java 8 and JAVA_HOME is pointing to jdk
![dspotproblem](https://user-images.githubusercontent.com/36235771/41657064-9b07b9f0-7481-11e8-9396-3f97ba4c5d1a.png)

**Comment by danglotb** [comment] 2018-06-20 12:11
Hi @RicardoTej 

Could you enable the verbose mode using `--verbose` options and copy/paste the output?

Thank you.

**Comment by RicardoTej** [comment] 2018-06-20 12:34
yes, but I get the same output
![dspotproblem2](https://user-images.githubusercontent.com/36235771/41658537-3256fb96-7486-11e8-9efc-d76ed751371a.png)
Thank you.

**Comment by danglotb** [comment] 2018-06-20 19:49
This is weird, it seems like that the maven goal ends up with an error, but nothing is printed, even with the verbose mode.

Could you go to the root of the dhell project and type:

```
mvn dependency:build-classpath
```

and give me the output.

Thank you.

**Comment by RicardoTej** [comment] 2018-06-21 07:05
Good morning : 
this is the output of mvn dependency:build-classpath

![mvnbuildclasspath](https://user-images.githubusercontent.com/36235771/41702942-48f7a788-7521-11e8-9d80-b5c9856c36ae.png)

**Comment by RicardoTej** [comment] 2018-06-21 07:11
and this is the output in the debug mode -X

![mvnclasspathdebug](https://user-images.githubusercontent.com/36235771/41703221-1bb94b40-7522-11e8-9380-5244a8610231.png)

[mvnBuildPathDebug.txt](https://github.com/STAMP-project/dspot/files/2122517/mvnBuildPathDebug.txt)

Thank you.

**Comment by danglotb** [comment] 2018-06-21 07:47
Hi @RicardoTej 

According to [this](https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#load(java.io.Reader)), the problem is that you provide a path with backslash `\` rather than `/`. The method `load(java.io.Reader)` of `Properties` uses the backslash `\` to escape characters.

I suggest you replace all the backslash `\` in your `project` property by a forward slash `/`.

**Comment by RicardoTej** [comment] 2018-06-21 08:47
Hello :
 I have tried in a freshly cloned dhell project using the getting started dspot.properties but the problem persists.

![dspotproblem21_6](https://user-images.githubusercontent.com/36235771/41708150-4c96552a-752f-11e8-91df-a9873e41b89a.png)

**Comment by danglotb** [comment] 2018-06-21 09:09
Hi @RicardoTej 

Are you using the [dhell](https://github.com/STAMP-project/dhell) project from STAMP repositories?
In this project, there is no module named `module1`. 

I just updated the file `dhell.dspot` in the project `dhell` with corrected properties.

Could you please:
1. pull the `dhell` project, _i.e._ going to the root of the `dhell` and launch `git pull`
2. then, run `dspot` from the same directory, _i.e._ the root of the `dhell` with the same command that u used.

Cheers,

**Comment by RicardoTej** [comment] 2018-06-21 09:53
Yes, I'm using the STAMP dhell, module1 comes from the dspot.properties :

 # Path to the current module where we want to execute DSpot, relative to the project root
targetModule=module1/

I didn't realize that it was just an example and there isn't a module named module1 in dhell.

I have updated my dhell and executed DSpot without the targetModule parameter in DSpot properties, and now I get the same problem as Jesus

![dspotproblem21_6 2](https://user-images.githubusercontent.com/36235771/41711934-e0f9ef3e-7538-11e8-875c-b89cbfbb9ff6.png)

Thank you !

**Comment by danglotb** [comment] 2018-06-21 10:34
According to the trace, your maven installation is misconfigured, such as @arnobl

You have the same error message: 

`[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?`

Could you please, fix your maven installation and re-try?

**Comment by RicardoTej** [comment] 2018-06-22 11:00
Good morning :

my JAVA_HOME is pointing to jdk, but the internal java.home of Maven points always to the jre in the jdk

https://stackoverflow.com/questions/15279586/java-home-in-maven 

and Maven is using java 8 that is correct, so I'm not sure about what to change in the Maven configuration

Thank you

**Comment by danglotb** [comment] 2018-10-02 12:52
I consider this issue too old and I close it. If you have new troubles, reopen it or open a new Issue. Thank you.

**Closed by danglotb** 2018-10-02 12:52 UTC
Labels: bug
