### ISSUE TITLE
Failure to execute DSpot on WaarpR66

### ISSUE THREAD

**Issue by slauriere** [STAMP-project/dspot#283] opened 2017-12-13 15:19 UTC
Steps to reproduce:

```
git clone https://github.com/waarp/WaarpR66.git
```

dspot.properties:
```
#relative path to the project root from dspot project
project=.
#relative path to the source project from the project properties
src=src/main/java
#relative path to the test source project from the project properties
testSrc=src/test/java
#srcResources=src/main/resources/
#testResources=src/test/resources/
#java version used
javaVersion=8
# (optional) path to the output folder, default to "output_diversify"
outputDirectory=dspot-out/
# (optional) filter on the package name containing tests to be amplified ("example" => "example.*"
filter=org.waarp*
```

Output exception:
```
4:13:48 PM PIT >> INFO : MINION : 4:13:48 PM PIT >> SEVERE : Description [testClass=org.waarp.openr66.protocol.networkhandler.NetworkTransactionTest, name=testisBlacklistedPreventNPE(org.waarp.openr66.protocol.networkhandler.NetworkTransactionTest)]
java.lang.ExceptionInInitializerError
	a
4:13:48 PM PIT >> INFO : MINION : t org.waarp.openr66.protocol.configuration.Configuration.computeNbThreads(Configuration.java:1068)
	at org.waarp.openr66.protocol.configuration.Configuration.<init>(Configuration.java:575)
	at org.waarp.openr66.protocol.configuration.Configuration.<clinit>
4:13:48 PM PIT >> INFO : MINION : (Configuration.java:53)
	at org.waarp.openr66.protocol.networkhandler.NetworkTransaction.isBlacklisted(NetworkTransaction.java:800)
	at org.waarp.openr66.protocol.networkhandler.NetworkTransactionTest.testisBlacklistedPreventNPE(NetworkTransactionTest.java
4:13:48 PM PIT >> INFO : MINION : :9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.re
4:13:48 PM PIT >> INFO : MINION : flect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMetho
4:13:48 PM PIT >> INFO : MINION : d.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(Block
4:13:48 PM PIT >> INFO : MINION : JUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.jun
4:13:48 PM PIT >> INFO : MINION : it.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363
4:13:48 PM PIT >> INFO : MINION : )
	at org.pitest.junit.adapter.CustomRunnerExecutor.run(CustomRunnerExecutor.java:42)
	at org.pitest.junit.adapter.AdaptedJUnitTestUnit.execute(AdaptedJUnitTestUnit.java:85)
	at org.pitest.coverage.execute.CoverageDecorator.execute(CoverageDecorator.java:5
4:13:48 PM PIT >> INFO : MINION : 0)
	at org.pitest.testapi.execute.containers.UnContainer.execute(UnContainer.java:32)
	at org.pitest.testapi.execute.Pitest.executeTests(Pitest.java:57)
	at org.pitest.testapi.execute.Pitest.run(Pitest.java:48)
	at org.pitest.coverage.execute.CoverageWorke
4:13:48 PM PIT >> INFO : MINION : r.run(CoverageWorker.java:51)
	at org.pitest.coverage.execute.CoverageMinion.main(CoverageMinion.java:91)
Caused by: java.util.MissingResourceException: Can't find bundle for base name messages, locale en
	at java.util.ResourceBundle.throwMissingResourceEx
4:13:48 PM PIT >> INFO : MINION : ception(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
	at org.waarp.openr66.protocol.configuration.Messages.init(Messages.java:27)
	at org.waar
4:13:48 PM PIT >> INFO : MINION : p.openr66.protocol.configuration.Messages.<clinit>(Messages.java:17)
	... 30 more

4:13:48 PM PIT >> SEVERE : Description [testClass=org.waarp.openr66.protocol.networkhandler.NetworkTransactionTest, name=testisBlacklistedPreventNPE(org.waarp.openr66.protocol.networkhandler.NetworkTransactionTest)] did not pass without mutation.
4:13:48 PM PIT >> INFO : Calculated coverage in 2 seconds.
-[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.080 s
[INFO] Finished at: 2017-12-13T16:13:48+01:00
[INFO] Final Memory: 22M/250M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.2.4:mutationCoverage (default-cli) on project WaarpR66: Execution default-cli of goal org.pitest:pitest-maven:1.2.4:mutationCoverage failed: All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
[ERROR] See http://pitest.org for more details.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:180)
	at fr.inria.diversify.dspot.selector.PitMutantScoreSelector.init(PitMutantScoreSelector.java:59)
	at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:102)
	at fr.inria.stamp.Main.run(Main.java:49)
	at fr.inria.stamp.Main.main(Main.java:32)
Caused by: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
	at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:177)
	... 4 more
```

while the existing test suite passes

**Comment by monperrus** [comment] 2018-02-16 13:40
Does WaarpR66 use generated code? Is it the same root cause as #264?

**Comment by monperrus** [comment] 2018-03-07 13:55
@slauriere Does WaarpR66 use generated code? Is it the same root cause as #264?

**Comment by slauriere** [comment] 2018-03-08 10:35
@monperrus I checked with the project developers and I confirm that some code (one or two classes) is generated at compilation time. One generated class gets probably imported by the test class raising the error.

**Comment by danglotb** [comment] 2018-03-09 11:53
Hi @slauriere 

Would you mind to retry? **DSpot** should now support generate sources thanks to #343.

You will have to build **DSpot** from the source, after pulling the repository, or re-clone it:

```sh
git clone https://github.com/STAMP-project/dspot.git
cd dspot
mvn install -DskipTests
```

and then run again on **WaarpR66**. 

You will have to modify the dspot.properties, to indicate that you have additional elements:

```
additionalClasspathElements=target/generated-sources
```

I am planning to make a release soon.

**Comment by danglotb** [comment] 2018-03-16 09:37
I am closing this issues. If you have any trouble, reopen it or open a new issue.

**Closed by danglotb** 2018-03-16 09:37 UTC
