### ISSUE TITLE
Running DSpot on TellU use case: tellulib

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/dspot#291] opened 2017-12-19 10:20 UTC
A little report of trying DSpot today, 19.12.2017:

mvn compile ok, mvn test fails with a few errors
Downloaded 1.0.4 jar from releases, used that for the rest.
Ran the example (copied the 1.0.4 release into dspot/target).
Seemed to run ok, put produced the following:
======= REPORT =======
Initial instruction coverage: 0 / 37
0,00%
Amplification results with 6 amplified tests.
Amplified instruction coverage: 0 / 37
0,00%

Tried on a single tellu project - tellulib - a single-module maven project with a limited scope and a small set of unit tests which run fast.
java -cp dspot-1.0.4-jar-with-dependencies.jar fr.inria.stamp.Main --path-to-properties dspot.properties --verbose
Stopped quickly with exception:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
        at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:179)
        at fr.inria.diversify.dspot.selector.PitMutantScoreSelector.init(PitMutantScoreSelector.java:59)
        at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:105)
        at fr.inria.stamp.Main.run(Main.java:53)
        at fr.inria.stamp.Main.run(Main.java:75)
        at fr.inria.stamp.Main.main(Main.java:37)
Caused by: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
        at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:176)
        ... 5 more
```

**Comment by danglotb** [comment] 2017-12-19 10:33
Hello @ltboye 

Thank you for trying **DSpot**!

>Seemed to run ok, put produced the following:
>======= REPORT =======
>Initial instruction coverage: 0 / 37
>0,00%
>Amplification results with 6 amplified tests.
>Amplified instruction coverage: 0 / 37
>0,00%

The output is wrong, it should be:

```
======= REPORT =======
Initial instruction coverage: 33 / 37
89.19%
Amplification results with 27 amplified tests.
Amplified instruction coverage: 37 / 37
100.00%
```

Would you mind to expose the command line used, and also where you use it (from which directory)? 
The documentation is probably not clear about that.

>Stopped quickly with exception:
>Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Maven build >failed! Enable verbose mode for more information (--verbose)

Okay, could you please, give me the properties file used (_i.e._ the content of ` dspot.properties`)?

Also, could you copy/paste the results of the execution of the maven goals? It should be just above the exception you gave, since you enabled the `verbose` mode with `--verbose`.

Thank again!

Cheers,

-- Benjamin.

**Comment by ltboye** [comment] 2017-12-19 11:54
Regarding example:
Command line was based on readme:
java -jar target/dspot-1.0.4-jar-with-dependencies.jar --example
I ran this in the dspot folder, after placing the jar in target. 
I also tried running one level up, in the folder of the dspot-parent pom, placing the jar in its target, but then it does not find the resources.

**Comment by ltboye** [comment] 2017-12-19 12:08
Regarding tellulib:
Properties:
# Relative path to the project root.
project=.
# Relative path to the source project from this properties file
src=src/main/java/
# Relative path to the test source project from this properties file
testSrc=src/test/java
# Java version used
javaVersion=8

I was experimenting a bit with the project path property, without improving the result.
Looking at the output again, it says: Failed to execute goal org.pitest:pitest-maven:1.1.5:mutationCoverage (default-cli) on project util: Execution default-cli of goal org.pitest:pitest-maven:1.1.5:mutationCoverage failed: No mutations found. This probably means there is an issue with either the supplied classpath or filters.

I have attached the complete output.
[output.txt](https://github.com/STAMP-project/dspot/files/1571584/output.txt)

**Comment by danglotb** [comment] 2017-12-19 12:32
Hi again,

In one hand, I don't know what is happening for the example, and I am sorry. On my side it works perfectly so I cannot understand the problem (such as the test...)

In the other hand, I can help you for your use case.

The error is that PIT does not find your tests. From your output we see:
>13:04:02 PIT >> INFO : SLAVE : 13:04:02 PIT >> INFO : 0 tests received

If we look at the goals ran:

> org.pitest:pitest-maven:mutationCoverage -DwithHistory -DtargetClasses=null -DreportsDirectory=target/pit-reports -DoutputFormats=CSV,HTML -DtimeoutConst=10000 -DjvmArgs=16G -DmutationEngines=gregor -Dmutators=ALL -DadditionalClasspathElements=target/dspot/dependencies/

The values of the `-DtargetClasses` flag is **null**. According to your properties file, you did not give a value for the property `filter`.

This property is used to match your classes. You can use a regex to give all the classes.

For example, I have the following hierarchy of classes:

```
+- stamp
    +- inria
         - dspot
         - descartes
    +- tellu
         - core
    |    - common
```

If I want to amplify all the classes of `tellu` package, I'll use: `filter=stamp.tellu.*`
If I want to amplify all the classes of the project, I'll use: `filter=stamp.*`
If I want to amplify all the classes of `tellu.core` sub-package, I'll use: `filter=stamp.tellu.core.*`

etc...

If you have any trouble, do not hesitate.

-- Benjamin.

**Comment by ltboye** [comment] 2017-12-19 13:02
Yes, adding the filter it works!

It ran for about 9 minutes. It produced modified tests, but from the report summary I assume it didn't manage to find anything useful:
======= REPORT =======
PitMutantScoreSelector:
The original test suite kills 2724 mutants
The amplification results with 0 new tests
it kills 0 more mutants

Maybe the original tests are extremely good :). Or I need to use something else than the default mutators. I have attached the last part of the output.
[output-end.txt](https://github.com/STAMP-project/dspot/files/1571702/output-end.txt)

**Comment by danglotb** [comment] 2017-12-19 13:27
Nice! Indeed, the process finish but unsuccessful to amplify new test...

> Maybe the original tests are extremely good :)

Yes, maybe :). 

But, we can try others configurations of **DSpot** to try to kill more mutants.

By default, **DSpot** tries only to add new assertions on existing test cases. That is to say, that **DSpot** does not modify the inputs of tests.

To allows **DSpot** to modifies inputs, you have to add the flag `--amplfiers <list_of_input_modification>` to your command line.

The values available for `<list_of_input_modification>` are:
* TestDataMutator: modifies all types of literals, _i.e._ String, numbers and booleans
* MethodAdd: duplicates an existing method call
* MethodRemove: removes an existing method call
* StatementAdd: generates a method call on existing objects of the test (selected randomly). If needed, **DSpot** generates objects to give them as parameters to the method call added.

The elements must be separated by `:`. For instance I want to use both TestDataMutator and StatementAdd, I'll use: `--amplfiers TestDataMutator:StatementAdd`.

You can also play with the options `--iteration <integer>` which specify the number of time that **DSpot** will apply the main loop (Input Modification, Assertion Generation and Test Selection). By default it is set to 3, but be careful, it can take time. I suggest you to reduce it to 1 if you add amplifiers (`--iteration 1`). 

The more you use different kind of amplifiers and iteration, the more **DSpot** will modifies inputs, and so try amplified tests.

Cheers.

**Comment by ltboye** [comment] 2017-12-20 08:53
Separating amplifiers with : isn't working for me. I tried --amplifiers TestDataMutator:StatementAdd, and it failed because it was looking for an enum constant named "TestDataMutator:StatementAdd".

Trying now with a single amplifier.

**Comment by danglotb** [comment] 2017-12-20 11:40
Oh, it is probably because you are on Windows. My bad, you have to use `;` I think but I am not sure.

Anyway, it should be the path separator of the system.

>Trying now with a single amplifier.

Could you please share the result when you succeed? Thank you again :)

**Comment by ltboye** [comment] 2017-12-20 11:47
I ran with --amplifiers TestDataMutator --iteration 2
Runtime 139 minutes
Same results as before, with 0 new tests

I can try each amplifier in turn, to see if any of them finds any new tests.

**Comment by ltboye** [comment] 2017-12-20 14:10
Some statistics on the tellulib project which may be of use:

Unit tests: 51
mvn test runtime: 2 sec
Jacoco instruction coverage: 33%
Pitest mutation score: 29%
Pitest-Descartes mutation score: 35%

**Comment by ltboye** [comment] 2017-12-21 10:44
Now I've finished with the other amplifiers, one by one, 2 iterations:
* MethodAdd: don't have the runtime (1-2 hours), no new tests
* MethodRemove: 26 minutes, no new tests
* StatementAdd: 55 minutes, 2 new tests killing 1 more mutant

How do I find the new tests?

**Comment by danglotb** [comment] 2017-12-21 11:41
It should be in a folder, named `output` by default.

You will have 3 files:
1. a txt file, with general results about the amplification.
2. a json file, with detail on which mutant is killed, by each amplified test, etc...
3. the .java of the amplified test class

**Comment by ltboye** [comment] 2017-12-21 13:36
Yes. The problem is that there are a number of test classes, and separate json and txt files for each. It would be nice to easily see which class has the new tests. But I was able to find it.

I include the class here. It is one I was not familiar with. The first two tests are from the original code, and the last two were added by DSpot. Don't the two new tests do the same as testParseInvalid? Just that testParseInvalid has the expectation of an exception in the annotation.

**Comment by danglotb** [comment] 2017-12-21 13:39
Hi @ltboye 

Would you mind to share the amplified test class result?

Thank you.

**Comment by ltboye** [comment] 2017-12-21 13:45
It didn't like the file, so I paste the content:

package no.tellu.lib.util;

import java.text.ParseException;
import org.junit.Assert;
import org.junit.Test;

public class AmplDateTimeTestMs {
    void parseAndFormat(String s) throws ParseException {
        DateTimeMs dt = DateTimeMs.parse(s);
        Assert.assertEquals(s, dt.toString());
    }

    @Test
    public void testParseAndFormat() throws ParseException {
        parseAndFormat("2017-12-31T12:33:44.999");
    }

    @Test(expected = ParseException.class)
    public void testParseInvalid() throws ParseException {
        DateTime.parse("2017-12-31 12:33:44.999");
    }

    @Test(timeout = 10000)
    public void testParseInvalid_failAssert0() throws ParseException {
        // AssertGenerator generate try/catch block with fail statement
        try {
            DateTime.parse("2017-12-31 12:33:44.999");
            org.junit.Assert.fail("testParseInvalid should have thrown ParseException");
        } catch (ParseException eee) {
        }
    }

    /* amplification of no.tellu.lib.util.DateTimeTestMs#testParseInvalid */
    @Test(timeout = 10000)
    public void testParseInvalid_sd2_failAssert0() throws ParseException {
        // AssertGenerator generate try/catch block with fail statement
        try {
            // StatementAdd: generate variable from return value
            DateTime __DSPOT_invoc_1 = DateTime.parse("2017-12-31 12:33:44.999");
            // StatementAdd: add invocation of a method
            __DSPOT_invoc_1.toString();
            org.junit.Assert.fail("testParseInvalid_sd2 should have thrown ParseException");
        } catch (ParseException eee) {
        }
    }
}

**Comment by danglotb** [comment] 2018-02-08 11:58
Hi @ltboye 

sorry for the delay between my answers.

Would you mind to share a pointer to your sources? I would like to have look deeper in this problem.

Thank you very much.

**Comment by ltboye** [comment] 2018-02-09 08:56
Sure. I tried to add you as a collaborator on the GitHub repo, but it says we need to buy more seats for the Tellu GitHub account. I will see if we can do this, otherwise find some other way.

**Comment by ltboye** [comment] 2018-02-13 09:56
Now you should have access to the TelluLib repo.

**Comment by danglotb** [comment] 2018-03-02 12:42
I have access to the repo, but it seems that the pom parent is missing. See the dedicated issue on your repository.

Cheers,

-- Benjamin.

**Comment by danglotb** [comment] 2018-03-05 09:41
I am currently trying to reproduce your exp.

I hit a bug right now:

```
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.3.0:mutationCoverage (default-cli) on project util: 
Execution default-cli of goal org.pitest:pitest-maven:1.3.0:mutationCoverage failed: 
(Ljava/io/StreamTokenizer;Ljava/lang/StringBuilder;)B does not return integer type -> [Help 1]
```

obtained by running:

```
mvn clean test org.pitest:pitest-maven:1.3.0:mutationCoverage \
-DwithHistory -DtargetClasses="no.*" \
-DreportsDirectory=target/pit-reports \
-DoutputFormats=CSV,HTML -DtimeoutConst=10000 \
-DjvmArgs=16G \
-DmutationEngines=gregor -Dmutators=ALL \
-DadditionalClasspathElements=target/dspot/dependencies/
```

By browsing the code, there is only on method that match the error message:

```java
public static byte parsePath(StreamTokenizer st, StringBuilder sb) throws IOException
```

in `no.tellu.lib.data.model`

@oscarlvp do you know this error? it seems that  **PIT** replace a `byte` by an int, and then crash.

This bug occurs when I use **PIT** `1.3.0`, but does not when I use **PIT** `1.2.0`.

The problem is, that **DSpot** is configured to use **PIT** `1.3.0`, and this hardcoded. 

I am gonna introduce a way to be more flexible.

**Comment by danglotb** [comment] 2018-03-09 12:17
Hello @ltboye 

With #348, we able to specify a version of PIT.

You just need to add: `pitVersion=1.2.0` to your `.properties` file.

I just made a release, please download the new jar with dependencies.

Cheers.

**Comment by oscarlvp** [comment] 2018-03-09 15:27
Hi @danglotb , sorry I saw this just now. I haven't used version 1.3.0.

**Comment by danglotb** [comment] 2018-03-16 09:49
I am closing this issues. If you have any trouble, reopen it or open a new issue.

**Closed by danglotb** 2018-03-16 09:49 UTC
