### ISSUE TITLE
DSpot not working with Dhell

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#306] opened 2018-01-26 11:04 UTC
**Issue Type**: bug
**Description**: DSpot fails with an exception when it is been applied to DHell project, following the DSpot tutorial for Dummies. BTW, this tutorial has a number of errors due to updates in the DSpot folder structure and the name of DSpot jars build in target folder, that I fix in the PR I submitted.
As DSpot is not longer working with DHell, which is its testing example, I encourage to fix it asap, as I guess DSpot will not work with UC projects, as I see other UC providers are reporting.
**Reproducibility**: always 
**Severity**: block 
**Tool**: Descartes PITest, version 26/01/18
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**:
Followed DSpot tutorial for Dummies with this fixed dspot.properties in dhell folder:
```
#relative path to the target project root from dspot execution
project=../../dhell
#relative path to the source project from the project properties
src=src/main/java/
#relative path to the test source project from the project properties
testSrc=src/test/java
#java version used
javaVersion=8
# (optional) path to the output folder, default to "output_diversify"
outputDirectory=dspot-out/
# (optional) filter on the package name containing tests to be amplified ("example" => "example.*"
filter=fr.inria.stamp.examples.dhell*
```
and this execution from dspot/dspot folder:
`java -jar target/dspot-1.0.6-SNAPSHOT-jar-with-dependencies.jar  -p ../../dhell/dspot.properties -i 1 -t  fr.inria.stamp.examples.dhell.HelloAppTest -a MethodAdd --verbose`
See execution logs in attached file:
[dspot_execution_on_dhell.txt](https://github.com/STAMP-project/dspot/files/1667502/dspot_execution_on_dhell.txt)

**Files**:
**Relationships**: 
**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by danglotb** [comment] 2018-01-26 12:15
It seems that the **dhell** project does not support the version _1.3.0_ of **PIT**.

In fact, when I run `mvn org.pitest:pitest-maven:1.2.0:mutationCoverage` at the root of **dhell* project everything goes find but when I run `mvn org.pitest:pitest-maven:1.3.0:mutationCoverage`, the same errors occur.

In fact, in **DSpot** the version of **PIT** is hard coded, because some test relies on the number of mutant generated by tests.

I don't really know **dhell**, but I'll investigate, also maybe @CaelInria can have a look. 

Thank you.

**Comment by jesus-gorronogoitia** [comment] 2018-01-26 12:45
Thanks, I though DHell was also yours. It would be great to have a controlled testing project for DSpot that we can use for our simple usage tests, without relying on testing it in our industrial cases (more complex), just for the sake of testing DSpot interface.

**Comment by jesus-gorronogoitia** [comment] 2018-01-26 12:51
BTW, the solution is pretty straightforward,
In dhell folder, pom.xml is referencing PITest 1.2.0 (I guess as required by Descartes), so just updating this version to 1.3.0 solves it.
@CaelInria: can we update this in Dhell source?

**Comment by CaelInria** [comment] 2018-01-26 13:01
@jesus-gorronogoitia : Yes of course, no problem.

**Comment by jesus-gorronogoitia** [comment] 2018-01-26 13:06
Can you directly modify pom.xml?, because if I have to do it by myself, I have to fork the repository, made and push the change to my fork repository and then create a PR. I think a PR approach is meant for significant changes, not for just fixing small thinks.

**Comment by danglotb** [comment] 2018-01-26 13:08
The problem is, that in **DSpot**, we use the version `1.3.0` of PIT, which is throwing the given errors. 

> In dhell folder, pom.xml is referencing PITest 1.2.0 (I guess as required by Descartes), so just updating this version to 1.3.0 solves it.

This won't fix the problem, it will only throw the same errors when we run the provided scripts.

IMHO, We have two options: 

1. downgrading the version of PIT used inside **Dspot**.
2. upgrading the version of PIT inside the **dhell** AND fix java sources to make the mutation analysis pass.

-- Benjamin.

**Comment by jesus-gorronogoitia** [comment] 2018-01-26 13:18
Yes, I applied your second option, upgrading PIT version declared in dhell pom.xml, and it worked!
Am I not getting your point?

**Comment by danglotb** [comment] 2018-01-26 13:22
>Yes, I applied your second option, upgrading PIT version declared in dhell pom.xml, and it worked!
Am I not getting your point?

Really? I am a little bit confused! 

On my side, It does not work.

**Comment by jesus-gorronogoitia** [comment] 2018-01-26 13:31
I swear you! :)
I've just execute it again. 
This is the diff in dhell/pom.xml:
```
diff --git a/pom.xml b/pom.xml
index 7e8e431..3f87ae6 100644
--- a/pom.xml
+++ b/pom.xml
@@ -23,7 +23,7 @@
     <dependency>
       <groupId>org.pitest</groupId>
       <artifactId>pitest-maven</artifactId>
-      <version>1.2.0</version>
+      <version>1.3.0</version>
     </dependency>
   </dependencies>
```
See DSpot execution logs in attached file
[dspot_execution_on_dhell.txt](https://github.com/STAMP-project/dspot/files/1667850/dspot_execution_on_dhell.txt)

**Comment by danglotb** [comment] 2018-02-08 11:59
HI, @CaelInria 

Could confirm the fix?

Thank you.

**Comment by CaelInria** [comment] 2018-02-08 16:09
Hello,

Actually I ran PIT 1.3.0 and 1.3.1 on dhell, and it works.
But I ran dspot and it failed.
I pushed my pom and script files I used and I attached the traces file of dspot execution.
[dspot.traces.txt](https://github.com/STAMP-project/dspot/files/1707800/dspot.traces.txt)

**Comment by danglotb** [comment] 2018-02-09 12:02
Hello,

I don't get it. 

I followed the tutorial in **DSpot** for [dummies](https://github.com/STAMP-project/dspot/blob/master/docs/dspot-for-dummies.md) and everything went find.

It is a little bit confusing.

@CaelInria could please, provide the properties you used?

Thank you.

**Comment by CaelInria** [comment] 2018-02-09 18:25
There was a bug in the propertied file. I fixed it and it works. :-)

**Comment by danglotb** [comment] 2018-02-09 20:00
Okay nice, we can close this issue then.

**Closed by danglotb** 2018-02-09 20:00 UTC
