### ISSUE TITLE
flaky test: one test fails during build on some machines: testBuildNewAssert / testPitEvosuiteMode

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#255] opened 2017-12-05 13:32 UTC
I've just tried to build dspot with "mvn clean package" and got:

```
======= REPORT =======
Initial instruction coverage: 33 / 37
89.19%
Amplification results with 3 amplified tests.
Amplified instruction coverage: 33 / 37
89.19%

2017-12-05 14:26:41,080 INFO fr.inria.diversify.dspot.DSpot - Print TestSuiteExample2Ampl with 0 amplified test cases in target/trash/
2017-12-05 14:26:41,080 DEBUG spoon.Launcher - printing example.TestSuiteExample2Ampl to target/trash
2017-12-05 14:26:41,084 DEBUG spoon.Launcher - building sources: [/Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestSuiteExample2.java, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestResources.java, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestSuiteExample.java]
2017-12-05 14:26:41,084 DEBUG spoon.Launcher - build args: [-encoding, UTF-8, -cp, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/target/classes:/Users/vmassol/.m2/repository/junit/junit/4.11/junit-4.11.jar:/Users/vmassol/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:target/dspot/dependencies/:, -1.8, -preserveAllLocals, -noExit, -enableJavadoc, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestSuiteExample2.java, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestResources.java, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestSuiteExample.java]
2017-12-05 14:26:41,111 DEBUG spoon.Launcher - built in 27 ms
2017-12-05 14:26:41,111 DEBUG spoon.Launcher - building templates: []
2017-12-05 14:26:41,111 DEBUG spoon.Launcher - built in 0 ms
2017-12-05 14:26:41,111 DEBUG spoon.Launcher - model built in 27
2017-12-05 14:26:41,111 DEBUG spoon.Launcher - compiling sources: [/Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestResources.java, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestSuiteExample.java, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestSuiteExample2.java]
2017-12-05 14:26:41,112 DEBUG spoon.Launcher - compile args: [-encoding, UTF-8, -cp, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/target/classes:/Users/vmassol/.m2/repository/junit/junit/4.11/junit-4.11.jar:/Users/vmassol/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:target/dspot/dependencies/:, -d, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/target/test-classes, -1.8, -proc:none, -preserveAllLocals, -noExit, -enableJavadoc, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestSuiteExample2.java, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestResources.java, /Users/vmassol/dev/dspot/dspot/src/test/resources/test-projects/src/test/java/example/TestSuiteExample.java]
2017-12-05 14:26:41,138 DEBUG spoon.Launcher - compiled in 27 ms
1206 ms
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 38.691 sec

Results :

Failed tests:   testBuildNewAssert(fr.inria.diversify.dspot.assertGenerator.MethodsAssertGeneratorTest): expected:<....junit.Assert.assert[True(((fr.inria.sample.ClassWithBoolean)cl).getTrue());(..)
  testPitEvosuiteMode(fr.inria.diversify.mutant.pit.PitTest): expected:<8.0> but was:<9.0>

Tests run: 125, Failures: 2, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] dspot-parent ....................................... SUCCESS [  0.278 s]
[INFO] DSpot .............................................. FAILURE [03:04 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

A test is failing. It should get fixed. Even better, a release of Dspot should be done so that it could be used without having to build it :)

**Comment by vmassol** [comment] 2017-12-05 13:33
Note: going to skip the test with `-DskipTests`

**Comment by danglotb** [comment] 2017-12-05 14:57
There is a release available on github, see [here](https://github.com/STAMP-project/dspot/releases).

**Comment by vmassol** [comment] 2017-12-05 14:59
That's good but then we need to document it on the main webpage of dspot since right now the recommended way is to build dspot from sources.

**Comment by vmassol** [comment] 2017-12-05 15:00
I'll try to provide a PR soon

**Comment by monperrus** [comment] 2017-12-08 09:19
closed per #258 , thanks a lot @vmassol for your contribution to improve documentation

**Comment by monperrus** [comment] 2017-12-08 09:29
This is a flaky test related to configuration. Renamed the issue.

**Comment by danglotb** [comment] 2017-12-08 09:34
output of `mvn --version`:
```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.8.0-59-generic", arch: "amd64", family: "unix"
```

Command line: `mvn clean package`

**Comment by vmassol** [comment] 2017-12-08 09:55
ok still getting the issue (just tried today):

```
vmassol ~/dev/dspot (master) $ mvn --version
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=196m; support was removed in 8.0
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /Applications/apache-maven-3.5.2
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.1", arch: "x86_64", family: "mac"
```

**Comment by vmassol** [comment] 2017-12-08 09:56
Could it be that dspot doesn't build on mac?

**Comment by danglotb** [comment] 2017-12-08 10:04
>Maybe those parameters vary depending on the OS?

I don't think so, because @nicolabertazzo and @slauriere has the same issue than you, and they are running Ubuntu.

Could you please, try to find the full errors of 
` testBuildNewAssert(fr.inria.diversify.dspot.assertGenerator.MethodsAssertGeneratorTest): expected:<....junit.Assert.assert[True(((fr.inria.sample.ClassWithBoolean)cl).getTrue());(..)`

Because we don't have the actual value.

**Comment by monperrus** [comment] 2017-12-13 11:56
duplicate of #98

**Closed by monperrus** 2017-12-13 11:56 UTC
Labels: duplicate
