### ISSUE TITLE
Test errors building DSpot

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/dspot#555] opened 2018-09-24 13:39 UTC
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot
- **Execution Environment**: Windows 10
- **Reporter**: Lars Thomas Boye

#### Description
mvn test on DSpot fails for me. It gives the following error several places:

java.lang.RuntimeException: spoon.compiler.InvalidClassPathException: /C:/Users/Lars%20Thomas%20Boye/.m2/repository/junit/junit/4.12/junit-4.12.jar does not exist, it is not a valid folder

It seems to be a Windows path problem (the jar is in the repo).

**Comment by danglotb** [comment] 2018-09-25 12:10
Hello,

Could please try to run the test using the branch `danglotb/fix-win-compatibility`:

```
git remote add danglotb https://github.com/danglotb/dspot.git
git fetch danglotb fix-win-compatibility
git checkout fix-win-compatibility
mvn clean test
```

Thank you.

**Comment by ltboye** [comment] 2018-09-25 12:33
The results with this is
Tests run: 167, Failures: 2, Errors: 29, Skipped: 9

(Last part of) output attached.

[mvn clean test.txt](https://github.com/STAMP-project/dspot/files/2415185/mvn.clean.test.txt)

**Comment by danglotb** [comment] 2018-09-25 12:40
Thank you.

The issue is that some paths are starting with a `/`  while it should not on windows, _e.g._ `/C:/Users/Lars%20Thomas%20Boye/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar`

I keep searching.

**Comment by danglotb** [comment] 2019-04-15 07:56
Closing this issue. Please reopen it or open a new one. Thank you.

**Closed by danglotb** 2019-04-15 07:56 UTC
