### ISSUE TITLE
Add support for Ant projects

### ISSUE THREAD

**Issue by danzone** [STAMP-project/dspot#328] opened 2018-02-19 14:12 UTC
Motivations: For now, DSpot can only be run on Maven and Gradle projects. After the last meeting with several OW2 project leaders the needs for supporting also Ant projects emerged.

What: The task aims at adding a support for projects that use Ant. This is needed also to have DSpot amplification available also as a Ant Task (see task #317 ).

Expected changes: It consists of implementing the `AutomaticBuilder` interface for an Ant builder. It will allow the user to specify in the properties file or automatically detected (the `build.xml` exists) which tool his project is using.

**Comment by monperrus** [comment] 2018-02-23 13:35
To me it seems a duplicate of #317. @danzone, why do we need two issues here?

**Comment by danzone** [comment] 2018-02-23 13:58
You're right. The other activity should be to develop a custom Ant task able to invoke DSpot. I'm going to change title and description

**Closed** 2018-02-23 13:59 UTC
